### PR TITLE
Replaced some TODOs in Getting started guide

### PR DESCRIPTION
**Pull request by StefanSchubert**
I'm still not quite sure if the pigpiod is required but I added it as well as the pi4j install reference.

### CODE REVIEW

**Comment by FDelporte** [comment]
Thanks for your contribution! Very much appreciated!!
I have to commit this TODO has been left too long on this page by now...

**Comment by StefanSchubert** [comment]
Hi you assigned the request to me. Do I need to adopt something? (BTW this was my first merge request on github, took some time to figure it out, I'm not used to it yet).

**Comment by FDelporte** [comment]
Wow, honored to have received your first github merge request!!! Let me adapt and merge it (later).

**Comment by FDelporte** [comment]
No actual installation is needed for V2, pigpio is part of the dependencies. Closing this PR as the remaining TODOs in the docs have been solved.

**Pull request closed without merging**
